### Get all facture products
GET http://localhost:4000/factureproducts

### Get facture products by facture id
GET http://localhost:4000/factureproducts/factureid/2

### Get facture products by product id
GET http://localhost:4000/factureproducts/productid/3

### Create facture product
POST http://localhost:4000/factureproducts
Content-Type: application/json

{
    "factureId": 2,
    "productId": 3,
    "quantity": 2,
    "totalPrice": 50.75
}

### Delete facture product
DELETE http://localhost:4000/factureproducts/id/1
Content-Type: application/json
